apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinapi
  namespace: chainlink-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainlink-adapter
  template:
    metadata:
      labels:
        app: chainlink-adapter
    spec:
      containers:
      - env:
        - name: API_KEY
          value: FE90E0B9-1079-4563-809F-C1FACD80499D
        - name: EXPERIMENTAL_METRICS_ENABLED
          value: "true"
        - name: METRICS_PORT
          value: "9080"
        - name: RATE_LIMIT_API_TIER
          value: professional
        image: public.ecr.aws/chainlink/adapters/coinapi-adapter:1.0.5
        imagePullPolicy: Always
        name: coinapi
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 9080
          name: metrics
          protocol: TCP
