apiVersion: "v1"
kind: "Service"
metadata:
  name: "chainlink-deployment-service"
  namespace: "chainlink-fm"
  labels:
    app: "chainlink-node"
spec:
  ports:
  - name: "tcp"
    port: 6689
    targetPort: 6689
    protocol: TCP
  - name: "tcp2"
    port: 6688
    targetPort: 6688
    protocol: TCP
  selector:
    app: "chainlink-node"
  type: "LoadBalancer"
  loadBalancerIP: ""
